[development]
address = "0.0.0.0"
port = 8000
workers = 48
log = "normal"

[staging]
address = "0.0.0.0"
port = 80
workers = 48
log = "normal"

[production]
address = "0.0.0.0"
port = 80
workers = 48
log = "critical"
